
#Settings
[general]
	enable_anti_mob_farm = true
	#If enabled, the chunk that will get penalty will be the one where the mob died, instead of the one where the mob was spawned in
	USE_DEATH_LOCATION = false
	affect_animals = false
	affect_vanilla_loot = false
	affect_age_of_exile_loot = true
	affect_age_of_exile_exp = true
	affect_vanilla_exp_drops = false
	ONLY_AFFECT_MOBS_KILLED_BY_PLAYER = true
	#0.5 means Player has to do 50% of the mob's total HP in damage to get loot. This counts any player damage, even multiple players
	#Range: 0.0 ~ 1.0
	min_player_dmg_for_loot = 0.5
	#Every time you kill a mob, the chunk drop chance (originally 1), gets reduced by this amount
	#Range: 0.0 ~ 1.0
	mob_kill_chunk_penalty = 0.02
	#How much the chunk penalty regenerates passively per minute.
	#Range: 0.0 ~ 1.0
	penalty_regen_per_minute = 0.02
	#Free kills are kills in a chunk that don't trigger the penalty.
	#Range: 0 ~ 1000
	one_time_free_kills_per_chunk = 30
	#Looting Chests will add this many free kills
	#Range: 0 ~ 1000
	added_free_kills_on_chest_looted = 10
	#Gateway mod specific compatibility, relaxes the penalty for them.
	#Range: 0.0 ~ 100.0
	GATEWAYS_MOB_CHANCE_TO_NOT_PROC_PENALTY = 75.0
	excluded_dimensions = ["mmorpg:dungeon"]
	excluded_entities = []

